# Generated by Django 5.0.7 on 2025-09-20 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0004_room_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_letter', models.CharField(max_length=10)),
                ('year', models.PositiveIntegerField(default=1)),
                ('semester', models.CharField(max_length=20)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='master_data.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
