# Generated by Django 5.0.7 on 2025-09-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Laboratory'), ('seminar', 'Seminar')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('equipment', models.JSONField(blank=True, default=list)),
                ('constraints', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('qualifications', models.CharField(blank=True, max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('workload_capacity_hours', models.PositiveIntegerField(default=16)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='master_data.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('enrollment_no', models.CharField(max_length=50, unique=True)),
                ('current_semester', models.CharField(max_length=20)),
                ('major_subjects', models.JSONField(blank=True, default=list)),
                ('minor_subjects', models.JSONField(blank=True, default=list)),
                ('elective_preferences', models.JSONField(blank=True, default=list)),
                ('credit_requirements', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='master_data.department')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(help_text='NEP category: Major/Minor/SEC/VAC/AEC', max_length=50)),
                ('credits_theory', models.PositiveIntegerField(default=0)),
                ('credits_practical', models.PositiveIntegerField(default=0)),
                ('departments', models.ManyToManyField(blank=True, related_name='subjects', to='master_data.department')),
                ('prerequisites', models.ManyToManyField(blank=True, to='master_data.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('size', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='master_data.department')),
            ],
            options={
                'unique_together': {('department', 'semester', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise', to='master_data.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='master_data.subject')),
            ],
            options={
                'unique_together': {('faculty', 'subject')},
            },
        ),
    ]
