# Generated by Django 5.0.7 on 2025-09-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['department__code', 'semester', 'name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['enrollment_no']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['code']},
        ),
    ]
